// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlService.proto

package edu.uci.eecs.wukong.network.netty.service;

public final class ControlService {
  private ControlService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 type = 1;
    boolean hasType();
    int getType();
    
    // repeated string contents = 2;
    java.util.List<String> getContentsList();
    int getContentsCount();
    String getContents(int index);
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Command_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // repeated string contents = 2;
    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList contents_;
    public java.util.List<String>
        getContentsList() {
      return contents_;
    }
    public int getContentsCount() {
      return contents_.size();
    }
    public String getContents(int index) {
      return contents_.get(index);
    }
    
    private void initFields() {
      type_ = 0;
      contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      for (int i = 0; i < contents_.size(); i++) {
        output.writeBytes(2, contents_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contents_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(contents_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getContentsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uci.eecs.wukong.network.netty.service.ControlService.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uci.eecs.wukong.network.netty.service.ControlService.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Command_fieldAccessorTable;
      }
      
      // Construct using edu.uci.eecs.wukong.network.netty.service.ControlService.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDescriptor();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Command getDefaultInstanceForType() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Command build() {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uci.eecs.wukong.network.netty.service.ControlService.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Command buildPartial() {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Command result = new edu.uci.eecs.wukong.network.netty.service.ControlService.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new com.google.protobuf.UnmodifiableLazyStringList(
              contents_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.contents_ = contents_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uci.eecs.wukong.network.netty.service.ControlService.Command) {
          return mergeFrom((edu.uci.eecs.wukong.network.netty.service.ControlService.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uci.eecs.wukong.network.netty.service.ControlService.Command other) {
        if (other == edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.contents_.isEmpty()) {
          if (contents_.isEmpty()) {
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureContentsIsMutable();
            contents_.addAll(other.contents_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              ensureContentsIsMutable();
              contents_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string contents = 2;
      private com.google.protobuf.LazyStringList contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new com.google.protobuf.LazyStringArrayList(contents_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getContentsList() {
        return java.util.Collections.unmodifiableList(contents_);
      }
      public int getContentsCount() {
        return contents_.size();
      }
      public String getContents(int index) {
        return contents_.get(index);
      }
      public Builder setContents(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentsIsMutable();
        contents_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addContents(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllContents(
          java.lang.Iterable<String> values) {
        ensureContentsIsMutable();
        super.addAll(values, contents_);
        onChanged();
        return this;
      }
      public Builder clearContents() {
        contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addContents(com.google.protobuf.ByteString value) {
        ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:cloud.rpc.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cloud.rpc.Command)
  }
  
  public interface StatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 status = 1;
    boolean hasStatus();
    int getStatus();
  }
  public static final class Status extends
      com.google.protobuf.GeneratedMessage
      implements StatusOrBuilder {
    // Use Status.newBuilder() to construct.
    private Status(Builder builder) {
      super(builder);
    }
    private Status(boolean noInit) {}
    
    private static final Status defaultInstance;
    public static Status getDefaultInstance() {
      return defaultInstance;
    }
    
    public Status getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Status_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Status_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStatus() {
      return status_;
    }
    
    private void initFields() {
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.ControlService.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uci.eecs.wukong.network.netty.service.ControlService.Status prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uci.eecs.wukong.network.netty.service.ControlService.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Status_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.internal_static_cloud_rpc_Status_fieldAccessorTable;
      }
      
      // Construct using edu.uci.eecs.wukong.network.netty.service.ControlService.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDescriptor();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status getDefaultInstanceForType() {
        return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status build() {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uci.eecs.wukong.network.netty.service.ControlService.Status buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status buildPartial() {
        edu.uci.eecs.wukong.network.netty.service.ControlService.Status result = new edu.uci.eecs.wukong.network.netty.service.ControlService.Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uci.eecs.wukong.network.netty.service.ControlService.Status) {
          return mergeFrom((edu.uci.eecs.wukong.network.netty.service.ControlService.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uci.eecs.wukong.network.netty.service.ControlService.Status other) {
        if (other == edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 status = 1;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cloud.rpc.Status)
    }
    
    static {
      defaultInstance = new Status(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cloud.rpc.Status)
  }
  
  public static abstract class BlockingControlService
      implements com.google.protobuf.Service {
    protected BlockingControlService() {}
    
    public interface Interface {
      public abstract void perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BlockingControlService() {
        @java.lang.Override
        public  void perform(
            com.google.protobuf.RpcController controller,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
            com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done) {
          impl.perform(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.perform(controller, (edu.uci.eecs.wukong.network.netty.service.ControlService.Command)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void perform(
        com.google.protobuf.RpcController controller,
        edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
        com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.perform(controller, (edu.uci.eecs.wukong.network.netty.service.ControlService.Command)request,
            com.google.protobuf.RpcUtil.<edu.uci.eecs.wukong.network.netty.service.ControlService.Status>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.uci.eecs.wukong.network.netty.service.ControlService.BlockingControlService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Status.class,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request)
          throws com.google.protobuf.ServiceException {
        return (edu.uci.eecs.wukong.network.netty.service.ControlService.Status) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance());
      }
      
    }
  }
  
  public static abstract class NonBlockingControlService
      implements com.google.protobuf.Service {
    protected NonBlockingControlService() {}
    
    public interface Interface {
      public abstract void perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new NonBlockingControlService() {
        @java.lang.Override
        public  void perform(
            com.google.protobuf.RpcController controller,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
            com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done) {
          impl.perform(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.perform(controller, (edu.uci.eecs.wukong.network.netty.service.ControlService.Command)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void perform(
        com.google.protobuf.RpcController controller,
        edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
        com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.ControlService.getDescriptor().getServices().get(1);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.perform(controller, (edu.uci.eecs.wukong.network.netty.service.ControlService.Command)request,
            com.google.protobuf.RpcUtil.<edu.uci.eecs.wukong.network.netty.service.ControlService.Status>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.ControlService.Command.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.uci.eecs.wukong.network.netty.service.ControlService.NonBlockingControlService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.ControlService.Status> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Status.class,
            edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.uci.eecs.wukong.network.netty.service.ControlService.Status perform(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Command request)
          throws com.google.protobuf.ServiceException {
        return (edu.uci.eecs.wukong.network.netty.service.ControlService.Status) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.ControlService.Status.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_rpc_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_rpc_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_rpc_Status_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_rpc_Status_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ControlService.proto\022\tcloud.rpc\")\n\007Com" +
      "mand\022\014\n\004type\030\001 \002(\005\022\020\n\010contents\030\002 \003(\t\"\030\n\006" +
      "Status\022\016\n\006status\030\001 \002(\0052J\n\026BlockingContro" +
      "lService\0220\n\007perform\022\022.cloud.rpc.Command\032" +
      "\021.cloud.rpc.Status2M\n\031NonBlockingControl" +
      "Service\0220\n\007perform\022\022.cloud.rpc.Command\032\021" +
      ".cloud.rpc.StatusB.\n)edu.uci.eecs.wukong" +
      ".network.netty.service\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cloud_rpc_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cloud_rpc_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cloud_rpc_Command_descriptor,
              new java.lang.String[] { "Type", "Contents", },
              edu.uci.eecs.wukong.network.netty.service.ControlService.Command.class,
              edu.uci.eecs.wukong.network.netty.service.ControlService.Command.Builder.class);
          internal_static_cloud_rpc_Status_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cloud_rpc_Status_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cloud_rpc_Status_descriptor,
              new java.lang.String[] { "Status", },
              edu.uci.eecs.wukong.network.netty.service.ControlService.Status.class,
              edu.uci.eecs.wukong.network.netty.service.ControlService.Status.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
