// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package edu.uci.eecs.wukong.network.netty.service;

public final class DataService {
  private DataService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DatagramOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 serviceId = 1;
    boolean hasServiceId();
    int getServiceId();
    
    // repeated int32 data = 2;
    java.util.List<java.lang.Integer> getDataList();
    int getDataCount();
    int getData(int index);
  }
  public static final class Datagram extends
      com.google.protobuf.GeneratedMessage
      implements DatagramOrBuilder {
    // Use Datagram.newBuilder() to construct.
    private Datagram(Builder builder) {
      super(builder);
    }
    private Datagram(boolean noInit) {}
    
    private static final Datagram defaultInstance;
    public static Datagram getDefaultInstance() {
      return defaultInstance;
    }
    
    public Datagram getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Datagram_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Datagram_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 serviceId = 1;
    public static final int SERVICEID_FIELD_NUMBER = 1;
    private int serviceId_;
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServiceId() {
      return serviceId_;
    }
    
    // repeated int32 data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> data_;
    public java.util.List<java.lang.Integer>
        getDataList() {
      return data_;
    }
    public int getDataCount() {
      return data_.size();
    }
    public int getData(int index) {
      return data_.get(index);
    }
    
    private void initFields() {
      serviceId_ = 0;
      data_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasServiceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serviceId_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32(2, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serviceId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Datagram parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uci.eecs.wukong.network.netty.service.DataService.Datagram prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uci.eecs.wukong.network.netty.service.DataService.DatagramOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Datagram_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Datagram_fieldAccessorTable;
      }
      
      // Construct using edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDescriptor();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Datagram getDefaultInstanceForType() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Datagram build() {
        edu.uci.eecs.wukong.network.netty.service.DataService.Datagram result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uci.eecs.wukong.network.netty.service.DataService.Datagram buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uci.eecs.wukong.network.netty.service.DataService.Datagram result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Datagram buildPartial() {
        edu.uci.eecs.wukong.network.netty.service.DataService.Datagram result = new edu.uci.eecs.wukong.network.netty.service.DataService.Datagram(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceId_ = serviceId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uci.eecs.wukong.network.netty.service.DataService.Datagram) {
          return mergeFrom((edu.uci.eecs.wukong.network.netty.service.DataService.Datagram)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uci.eecs.wukong.network.netty.service.DataService.Datagram other) {
        if (other == edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance()) return this;
        if (other.hasServiceId()) {
          setServiceId(other.getServiceId());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasServiceId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serviceId_ = input.readInt32();
              break;
            }
            case 16: {
              ensureDataIsMutable();
              data_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addData(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 serviceId = 1;
      private int serviceId_ ;
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServiceId() {
        return serviceId_;
      }
      public Builder setServiceId(int value) {
        bitField0_ |= 0x00000001;
        serviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 data = 2;
      private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<java.lang.Integer>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      public int getDataCount() {
        return data_.size();
      }
      public int getData(int index) {
        return data_.get(index);
      }
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cloud.rpc.Datagram)
    }
    
    static {
      defaultInstance = new Datagram(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cloud.rpc.Datagram)
  }
  
  public interface FeedbackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 returnId = 1;
    boolean hasReturnId();
    int getReturnId();
  }
  public static final class Feedback extends
      com.google.protobuf.GeneratedMessage
      implements FeedbackOrBuilder {
    // Use Feedback.newBuilder() to construct.
    private Feedback(Builder builder) {
      super(builder);
    }
    private Feedback(boolean noInit) {}
    
    private static final Feedback defaultInstance;
    public static Feedback getDefaultInstance() {
      return defaultInstance;
    }
    
    public Feedback getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Feedback_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Feedback_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 returnId = 1;
    public static final int RETURNID_FIELD_NUMBER = 1;
    private int returnId_;
    public boolean hasReturnId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getReturnId() {
      return returnId_;
    }
    
    private void initFields() {
      returnId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasReturnId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, returnId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, returnId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uci.eecs.wukong.network.netty.service.DataService.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uci.eecs.wukong.network.netty.service.DataService.Feedback prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uci.eecs.wukong.network.netty.service.DataService.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Feedback_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.internal_static_cloud_rpc_Feedback_fieldAccessorTable;
      }
      
      // Construct using edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        returnId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDescriptor();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback getDefaultInstanceForType() {
        return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance();
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback build() {
        edu.uci.eecs.wukong.network.netty.service.DataService.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uci.eecs.wukong.network.netty.service.DataService.Feedback buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uci.eecs.wukong.network.netty.service.DataService.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback buildPartial() {
        edu.uci.eecs.wukong.network.netty.service.DataService.Feedback result = new edu.uci.eecs.wukong.network.netty.service.DataService.Feedback(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.returnId_ = returnId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uci.eecs.wukong.network.netty.service.DataService.Feedback) {
          return mergeFrom((edu.uci.eecs.wukong.network.netty.service.DataService.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uci.eecs.wukong.network.netty.service.DataService.Feedback other) {
        if (other == edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance()) return this;
        if (other.hasReturnId()) {
          setReturnId(other.getReturnId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasReturnId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              returnId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 returnId = 1;
      private int returnId_ ;
      public boolean hasReturnId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getReturnId() {
        return returnId_;
      }
      public Builder setReturnId(int value) {
        bitField0_ |= 0x00000001;
        returnId_ = value;
        onChanged();
        return this;
      }
      public Builder clearReturnId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        returnId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cloud.rpc.Feedback)
    }
    
    static {
      defaultInstance = new Feedback(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cloud.rpc.Feedback)
  }
  
  public static abstract class BlockingDataService
      implements com.google.protobuf.Service {
    protected BlockingDataService() {}
    
    public interface Interface {
      public abstract void send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BlockingDataService() {
        @java.lang.Override
        public  void send(
            com.google.protobuf.RpcController controller,
            edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
            com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done) {
          impl.send(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.send(controller, (edu.uci.eecs.wukong.network.netty.service.DataService.Datagram)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void send(
        com.google.protobuf.RpcController controller,
        edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
        com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.send(controller, (edu.uci.eecs.wukong.network.netty.service.DataService.Datagram)request,
            com.google.protobuf.RpcUtil.<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.uci.eecs.wukong.network.netty.service.DataService.BlockingDataService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.class,
            edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request)
          throws com.google.protobuf.ServiceException {
        return (edu.uci.eecs.wukong.network.netty.service.DataService.Feedback) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance());
      }
      
    }
  }
  
  public static abstract class NonBlockingDataService
      implements com.google.protobuf.Service {
    protected NonBlockingDataService() {}
    
    public interface Interface {
      public abstract void send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new NonBlockingDataService() {
        @java.lang.Override
        public  void send(
            com.google.protobuf.RpcController controller,
            edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
            com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done) {
          impl.send(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.send(controller, (edu.uci.eecs.wukong.network.netty.service.DataService.Datagram)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void send(
        com.google.protobuf.RpcController controller,
        edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
        com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.uci.eecs.wukong.network.netty.service.DataService.getDescriptor().getServices().get(1);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.send(controller, (edu.uci.eecs.wukong.network.netty.service.DataService.Datagram)request,
            com.google.protobuf.RpcUtil.<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.uci.eecs.wukong.network.netty.service.DataService.NonBlockingDataService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request,
          com.google.protobuf.RpcCallback<edu.uci.eecs.wukong.network.netty.service.DataService.Feedback> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.class,
            edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.uci.eecs.wukong.network.netty.service.DataService.Feedback send(
          com.google.protobuf.RpcController controller,
          edu.uci.eecs.wukong.network.netty.service.DataService.Datagram request)
          throws com.google.protobuf.ServiceException {
        return (edu.uci.eecs.wukong.network.netty.service.DataService.Feedback) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_rpc_Datagram_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_rpc_Datagram_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_rpc_Feedback_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_rpc_Feedback_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DataService.proto\022\tcloud.rpc\"+\n\010Datagr" +
      "am\022\021\n\tserviceId\030\001 \002(\005\022\014\n\004data\030\002 \003(\005\"\034\n\010F" +
      "eedback\022\020\n\010returnId\030\001 \002(\0052G\n\023BlockingDat" +
      "aService\0220\n\004send\022\023.cloud.rpc.Datagram\032\023." +
      "cloud.rpc.Feedback2J\n\026NonBlockingDataSer" +
      "vice\0220\n\004send\022\023.cloud.rpc.Datagram\032\023.clou" +
      "d.rpc.FeedbackB.\n)edu.uci.eecs.wukong.ne" +
      "twork.netty.service\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cloud_rpc_Datagram_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cloud_rpc_Datagram_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cloud_rpc_Datagram_descriptor,
              new java.lang.String[] { "ServiceId", "Data", },
              edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.class,
              edu.uci.eecs.wukong.network.netty.service.DataService.Datagram.Builder.class);
          internal_static_cloud_rpc_Feedback_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cloud_rpc_Feedback_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cloud_rpc_Feedback_descriptor,
              new java.lang.String[] { "ReturnId", },
              edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.class,
              edu.uci.eecs.wukong.network.netty.service.DataService.Feedback.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
